import 'package:flutter/widgets.dart';

const localeNames = <String, String>{
  'en-US': 'English',
  'zh-CN': '简体中文',
  'zh-TW': '繁體中文',
  'es-ES': 'Español',
  'pt-BR': 'Português (Brasil)',
  'id-ID': 'Bahasa Indonesia',
  'th-TH': 'ไทย',
  'vi-VN': 'Tiếng Việt',
  'ja-JP': '日本語',
  'ko-KR': '한국어',
  'fr-FR': 'Français',
  'de-DE': 'Deutsch',
  'ar-SA': 'العربية',
  'hi-IN': 'हिन्दी',
  'tr-TR': 'Türkçe',
};

const _zh = <String, String>{
  'forYou': '推荐',
  'following': '追剧',
  'drama': '剧场',
  'rewards': '奖励',
  'library': '片库',
  'me': '我的',
  'noDramas': '暂无短剧',
  'noFollowing': '还没有追剧',
  'noFollowingHint': '在推荐页点击“追剧”，收藏想继续观看的剧集。',
  'browseForYou': '去看推荐',
  'follow': '追剧',
  'followed': '已追剧',
  'episodes': '选集',
  'episodeCount': '集',
  'save': '收藏',
  'like': '点赞',
  'share': '分享',
  'unlock': '解锁',
  'watchAd': '观看广告',
  'playbackSpeed': '播放速度',
  'tracks': '字幕与配音',
  'retryPlayback': '重试播放',
  'signInToWatch': '登录后观看',
  'comments': '评论',
  'firstComment': '来发第一条评论吧',
  'viewer': '用户',
  'addComment': '添加评论',
  'subtitles': '字幕',
  'off': '关闭',
  'dubbing': '配音',
  'originalAudio': '原声',
  'apply': '应用',
  'dramaTheater': '短剧剧场',
  'trending': '热门',
  'romance': '爱情',
  'revenge': '逆袭',
  'billionaire': '总裁',
  'fantasy': '奇幻',
  'coinBalance': '金币余额',
  'signInToView': '登录后查看',
  'unavailable': '暂不可用',
  'rewardUnlocks': '看广告解锁剧集',
  'rewardUnlocksHint': '在锁定剧集中看完广告，即可直接解锁该集。',
  'moreCoins': '获取更多金币',
  'myLibrary': '我的片库',
  'watchHistory': '观看记录',
  'favorites': '收藏',
  'guest': '游客',
  'signInSync': '登录后同步购买与观看记录',
  'accountConnected': '账号已连接',
  'signIn': '登录',
  'membership': '会员',
  'plansBenefits': '套餐与权益',
  'coins': '金币',
  'balanceTransactions': '余额与明细',
  'messages': '消息',
  'updatesReplies': '通知与回复',
  'language': '语言',
  'settings': '设置',
  'settingsHint': '播放、字幕与隐私',
  'help': '帮助与客服',
  'helpHint': '常见问题与联系方式',
  'signOut': '退出登录',
  'searchDramas': '搜索短剧',
  'nothingHere': '这里还没有内容',
  'continueWatching': '继续观看',
  'chooseUnlock': '选择解锁方式',
  'watchAdUnlock': '看广告 · 解锁 1 集',
  'purchaseOptions': '购买选项',
  'tryAgain': '重试',
  'welcomeBack': '欢迎回来',
  'demoReady': '测试账号已准备好，点击继续即可测试点赞、评论和解锁。',
  'accountHint': '您的购买、收藏和观看记录将保存在账号中。',
  'email': '邮箱',
  'password': '密码',
  'continueEmail': '使用邮箱继续',
  'close': '关闭',
  'noMessages': '暂无消息',
};

extension AppStrings on BuildContext {
  bool get isChinese => Localizations.localeOf(this).languageCode == 'zh';

  String tr(String key, String english) =>
      isChinese ? (_zh[key] ?? english) : english;
}

Locale localeFromTag(String tag) {
  final parts = tag.split('-');
  return Locale(parts.first, parts.length > 1 ? parts[1] : null);
}
