export const platformRoles = [
  'platform_super_admin',
  'platform_operator',
  'content_reviewer',
  'platform_finance',
  'platform_support',
  'security_auditor',
] as const;

export const merchantRoles = [
  'merchant_owner',
  'merchant_admin',
  'content_operator',
  'merchant_finance',
  'marketing_operator',
  'merchant_support',
  'data_analyst',
] as const;

export type PlatformRole = (typeof platformRoles)[number];
export type MerchantRole = (typeof merchantRoles)[number];

export const permissionCatalog = [
  { code: 'platform.dashboard.read', module: 'platform', action: 'read', scope: 'platform' },
  { code: 'platform.analytics.read', module: 'analytics', action: 'read', scope: 'platform' },
  { code: 'platform.merchant.read', module: 'platform', action: 'read', scope: 'platform' },
  { code: 'platform.merchant.create', module: 'platform', action: 'create', scope: 'platform' },
  { code: 'platform.merchant.update', module: 'platform', action: 'update', scope: 'platform' },
  { code: 'platform.merchant.status', module: 'platform', action: 'status', scope: 'platform' },
  { code: 'platform.domain.manage', module: 'platform', action: 'manage', scope: 'platform' },
  { code: 'platform.staff.read', module: 'platform', action: 'read', scope: 'platform' },
  { code: 'platform.staff.manage', module: 'platform', action: 'manage', scope: 'platform' },
  {
    code: 'platform.staff.password_reset',
    module: 'platform',
    action: 'password_reset',
    scope: 'platform',
  },
  {
    code: 'platform.staff.session_revoke',
    module: 'platform',
    action: 'session_revoke',
    scope: 'platform',
  },
  { code: 'platform.customer.read', module: 'platform', action: 'read', scope: 'platform' },
  { code: 'platform.customer.manage', module: 'platform', action: 'manage', scope: 'platform' },
  {
    code: 'platform.customer.session_revoke',
    module: 'platform',
    action: 'session_revoke',
    scope: 'platform',
  },
  { code: 'platform.role.read', module: 'platform', action: 'read', scope: 'platform' },
  { code: 'platform.role.manage', module: 'platform', action: 'manage', scope: 'platform' },
  { code: 'platform.audit.read', module: 'platform', action: 'read', scope: 'platform' },
  { code: 'platform.audit.export', module: 'platform', action: 'export', scope: 'platform' },
  { code: 'platform.storage.read', module: 'storage', action: 'read', scope: 'platform' },
  { code: 'platform.storage.manage', module: 'storage', action: 'manage', scope: 'platform' },
  { code: 'platform.app_build.read', module: 'app_build', action: 'read', scope: 'platform' },
  { code: 'platform.app_build.manage', module: 'app_build', action: 'manage', scope: 'platform' },
  { code: 'platform.app_build.download', module: 'app_build', action: 'download', scope: 'platform' },
  { code: 'platform.content.read', module: 'content', action: 'read', scope: 'platform' },
  { code: 'platform.content.manage', module: 'content', action: 'manage', scope: 'platform' },
  { code: 'platform.content.publish', module: 'content', action: 'publish', scope: 'platform' },
  { code: 'platform.payment.read', module: 'payment', action: 'read', scope: 'platform' },
  { code: 'platform.payment.manage', module: 'payment', action: 'manage', scope: 'platform' },
  { code: 'content.license.read', module: 'content', action: 'read', scope: 'platform' },
  { code: 'content.license.manage', module: 'content', action: 'manage', scope: 'platform' },
  { code: 'finance.withdrawal.read', module: 'finance', action: 'read', scope: 'platform' },
  {
    code: 'finance.withdrawal.payout_account.read',
    module: 'finance',
    action: 'payout_account_read',
    scope: 'platform',
  },
  { code: 'finance.withdrawal.review', module: 'finance', action: 'review', scope: 'platform' },
  { code: 'finance.settlement.manage', module: 'finance', action: 'manage', scope: 'platform' },
  { code: 'finance.refund.read', module: 'finance', action: 'read', scope: 'platform' },
  { code: 'finance.refund.manage', module: 'finance', action: 'manage', scope: 'platform' },
  {
    code: 'finance.withdrawal.confirm_transfer',
    module: 'finance',
    action: 'confirm_transfer',
    scope: 'platform',
  },
  { code: 'tenant.dashboard.read', module: 'tenant', action: 'read', scope: 'tenant' },
  { code: 'tenant.analytics.read', module: 'analytics', action: 'read', scope: 'tenant' },
  { code: 'tenant.site.read', module: 'tenant', action: 'read', scope: 'tenant' },
  { code: 'tenant.site.manage', module: 'tenant', action: 'manage', scope: 'tenant' },
  { code: 'tenant.domain.read', module: 'tenant', action: 'read', scope: 'tenant' },
  { code: 'tenant.domain.manage', module: 'tenant', action: 'manage', scope: 'tenant' },
  { code: 'tenant.audit.read', module: 'tenant', action: 'read', scope: 'tenant' },
  { code: 'tenant.audit.export', module: 'tenant', action: 'export', scope: 'tenant' },
  { code: 'tenant.interaction.read', module: 'interaction', action: 'read', scope: 'tenant' },
  { code: 'tenant.interaction.manage', module: 'interaction', action: 'manage', scope: 'tenant' },
  {
    code: 'tenant.sensitive_word.manage',
    module: 'interaction',
    action: 'sensitive_word_manage',
    scope: 'tenant',
  },
  { code: 'content.drama.read', module: 'content', action: 'read', scope: 'tenant' },
  { code: 'content.drama.create', module: 'content', action: 'create', scope: 'tenant' },
  { code: 'content.drama.update', module: 'content', action: 'update', scope: 'tenant' },
  {
    code: 'content.drama.submit_review',
    module: 'content',
    action: 'submit_review',
    scope: 'tenant',
  },
  { code: 'commerce.catalog.read', module: 'commerce', action: 'read', scope: 'tenant' },
  { code: 'commerce.catalog.manage', module: 'commerce', action: 'manage', scope: 'tenant' },
  { code: 'commerce.payment.read', module: 'commerce', action: 'read', scope: 'tenant' },
  { code: 'commerce.payment.manage', module: 'commerce', action: 'manage', scope: 'tenant' },
  { code: 'commerce.order.read', module: 'commerce', action: 'read', scope: 'tenant' },
  { code: 'commerce.order.export', module: 'commerce', action: 'export', scope: 'tenant' },
  { code: 'commerce.balance.read', module: 'commerce', action: 'read', scope: 'tenant' },
  { code: 'commerce.referral.read', module: 'commerce', action: 'read', scope: 'tenant' },
  { code: 'commerce.referral.manage', module: 'commerce', action: 'manage', scope: 'tenant' },
  { code: 'commerce.refund.read', module: 'commerce', action: 'read', scope: 'tenant' },
  { code: 'commerce.refund.manage', module: 'commerce', action: 'manage', scope: 'tenant' },
  { code: 'commerce.withdrawal.read', module: 'commerce', action: 'read', scope: 'tenant' },
  { code: 'commerce.withdrawal.submit', module: 'commerce', action: 'submit', scope: 'tenant' },
  { code: 'tenant.staff.read', module: 'tenant', action: 'read', scope: 'tenant' },
  { code: 'tenant.staff.manage', module: 'tenant', action: 'manage', scope: 'tenant' },
  {
    code: 'tenant.staff.password_reset',
    module: 'tenant',
    action: 'password_reset',
    scope: 'tenant',
  },
  {
    code: 'tenant.staff.session_revoke',
    module: 'tenant',
    action: 'session_revoke',
    scope: 'tenant',
  },
  { code: 'tenant.customer.read', module: 'tenant', action: 'read', scope: 'tenant' },
  { code: 'tenant.customer.manage', module: 'tenant', action: 'manage', scope: 'tenant' },
  {
    code: 'tenant.customer.session_revoke',
    module: 'tenant',
    action: 'session_revoke',
    scope: 'tenant',
  },
  { code: 'tenant.legal.read', module: 'legal', action: 'read', scope: 'tenant' },
  { code: 'tenant.legal.manage', module: 'legal', action: 'manage', scope: 'tenant' },
  {
    code: 'tenant.privacy_request.read',
    module: 'legal',
    action: 'privacy_request_read',
    scope: 'tenant',
  },
  { code: 'tenant.role.read', module: 'tenant', action: 'read', scope: 'tenant' },
  { code: 'tenant.role.manage', module: 'tenant', action: 'manage', scope: 'tenant' },
  { code: 'tenant.storage.read', module: 'storage', action: 'read', scope: 'tenant' },
  { code: 'tenant.storage.manage', module: 'storage', action: 'manage', scope: 'tenant' },
  { code: 'tenant.communication.read', module: 'communication', action: 'read', scope: 'tenant' },
  { code: 'tenant.communication.manage', module: 'communication', action: 'manage', scope: 'tenant' },
  { code: 'notification.push.send', module: 'notification', action: 'send', scope: 'tenant' },
  { code: 'tenant.notification.read', module: 'notification', action: 'read', scope: 'tenant' },
  {
    code: 'tenant.notification.config.manage',
    module: 'notification',
    action: 'config_manage',
    scope: 'tenant',
  },
  {
    code: 'tenant.notification.campaign.manage',
    module: 'notification',
    action: 'campaign_manage',
    scope: 'tenant',
  },
] as const;

export type Permission = (typeof permissionCatalog)[number]['code'];

export const tenantOwnerPermissions = [
  'tenant.dashboard.read',
  'tenant.analytics.read',
  'tenant.site.read',
  'tenant.site.manage',
  'tenant.domain.read',
  'tenant.domain.manage',
  'tenant.audit.read',
  'tenant.audit.export',
  'tenant.interaction.read',
  'tenant.interaction.manage',
  'tenant.sensitive_word.manage',
  'content.drama.read',
  'content.drama.create',
  'content.drama.update',
  'content.drama.submit_review',
  'commerce.catalog.read',
  'commerce.catalog.manage',
  'commerce.payment.read',
  'commerce.payment.manage',
  'commerce.order.read',
  'commerce.order.export',
  'commerce.balance.read',
  'commerce.referral.read',
  'commerce.referral.manage',
  'commerce.refund.read',
  'commerce.refund.manage',
  'commerce.withdrawal.read',
  'commerce.withdrawal.submit',
  'tenant.staff.read',
  'tenant.staff.manage',
  'tenant.staff.password_reset',
  'tenant.staff.session_revoke',
  'tenant.customer.read',
  'tenant.customer.manage',
  'tenant.customer.session_revoke',
  'tenant.legal.read',
  'tenant.legal.manage',
  'tenant.privacy_request.read',
  'tenant.role.read',
  'tenant.role.manage',
  'tenant.storage.read',
  'tenant.storage.manage',
  'tenant.communication.read',
  'tenant.communication.manage',
  'notification.push.send',
  'tenant.notification.read',
  'tenant.notification.config.manage',
  'tenant.notification.campaign.manage',
] as const satisfies readonly Permission[];

export interface TenantSummary {
  id: string;
  code: string;
  name: string;
  status: 'active' | 'expired' | 'suspended';
  defaultLocale: string;
  timezone: string;
}
export { SUPPORTED_APP_LOCALES, APP_LOCALE_NAMES, APP_LOCALE_OPTIONS, type AppLocale } from './locales.js';
